# Library
```{r}
library(tidyverse)
library(tsibble)
library(sf)
library(spdep)

theme_set(theme_bw())
```

# Data ingestion and cleaning
```{r}
incidence_full <- read_csv("incidence_full.csv", show_col_types = FALSE)

incidence_full_renamed <- incidence_full %>%
  mutate(
    hospital = case_match(
      hospital,
      "BV QUAN 4" ~ "Bệnh viện Quận 4",
      "BV BENH NHIET DOI" ~ "Bênh viện Bệnh nhiệt đới TPHCM",
      "BV QUAN 11" ~ "Bệnh viện Quận 11",
      "NHI DONG 2" ~ "Bệnh viện Nhi đồng 2",
      "bv.nd2.khth@gmail.com" ~ "Bệnh viện Nhi đồng 2",
      "BV QUAN THU DUC" ~ "Bệnh viện Quận Thủ Đức",
      "BV BINH TAN" ~ "Bệnh viện Quận Bình Tân",
      "TRUNG VUONG" ~ "Bệnh viện Trưng Vương",
      "NHI DONG 1" ~ "Bệnh viện Nhi đồng 2",
      "BV BINH THANH" ~ "Bệnh viện Quận Bình Thạnh",
      "BV TAN BINH" ~ "Bệnh viện Quận Tân Bình",
      "THONG NHAT" ~ "Bệnh viện Thống Nhất",
      "NGUYEN TRAI" ~ "Bệnh viện Nguyễn Trãi",
      "BV QUAN 1" ~ "Bệnh viện Quận 1",
      "BV QUAN 8" ~ "Bệnh viện Quận 8",
      "BVDK CU CHI" ~ "Bệnh viện ĐKKV Củ Chi",
      "BV PHU NHUAN" ~ "Bệnh viện Quận Phú Nhuận",
      "BV TAN PHU" ~ "Bệnh viện Quận Tân Phú",
      "BV QUAN 6" ~ "Bệnh viện Quận 6",
      "BV HOC MON" ~ "Bệnh viện ĐKKV Hóc Môn",
      "BV BINH CHANH" ~ "Bệnh viện Huyện Bình Chánh",
      "BVDK THU DUC" ~ "Bệnh viện ĐKKV Thủ Đức",
      "BV QUAN 7" ~ "Bệnh viện Quận 7",
      "DK SAI GON" ~ "Bệnh viện đa khoa Sài Gòn",
      "BV QUAN 12" ~ "Bệnh viện Quận 12",
      "NHAN DAN GIA DINH" ~ "Bệnh viện Nhân Dân Gia Định",
      "BV NHA BE" ~ "Bệnh viện Huyện Nhà Bè",
      "BV DHYD" ~ "Bệnh viện Đại học Y Dược TPHCM",
      "BV QUAN 5" ~ "Bệnh viện Quận 5",
      "DK 30/4" ~ "Bệnh viện đa khoa 30/4 Tp.HCM",
      "NGUYEN TRI PHUONG" ~ "Bệnh viện Nguyễn Tri Phương",
      "CHO RAY" ~ "Bệnh viện Chợ Rẫy",
      "BENH VIEN 115" ~ "Bệnh viện Nhân Dân 115",
      "AN BINH" ~ "Bệnh viện An Bình",
      "BV QUAN 3" ~ "Bệnh viện Quận 3",
      "Bênh viện Pháp Việt" ~ "Bệnh viện Pháp Việt",
      .default = hospital
    ),
    hospital = tolower(hospital),
    date_admitted = yearweek(date_admitted)
  ) %>%
  filter(status == "in-patient", hospital != "trung tâm y tế  huyện vĩnh hưng")


incidence_ts_truncated <- incidence_full_renamed %>%
  filter(hospital == "bênh viện bệnh nhiệt đới tphcm" | hospital == "bệnh viện nhi đồng 2") %>%
  group_by(date_admitted) %>%
  tally() %>%
  mutate(date_admitted = as.Date(date_admitted))

incidence_ts_truncated %>% write_csv("incidence_ts_truncated.csv")


incidence_full_renamed %<>%
  group_by(date_admitted, hospital) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  complete(date_admitted, hospital)
incidence_full_renamed
```


# Time series - raw full
## In-patient + out-patient
```{r fig.width=10}
p1_df <- incidence_full %>%
  mutate(week_admitted = yearweek(date_admitted)) %>%
  group_by(week_admitted) %>%
  tally() %>%
  mutate(frame = "p1")

p1 <- p1_df %>%
  ggplot() +
  geom_step(aes(x = week_admitted, y = n)) +
  scale_x_yearweek(
    "Week admitted",
    breaks = as.Date(as.character(2000:2023), format = "%Y"),
    date_labels = "%Y"
  ) +
  scale_y_continuous("Case admission") +
  ggtitle("Weekly dengue case admission in HCMC (out-patient + in-patient)")
p1
```

## In-patient only
```{r fig.width=10}
p2_df <- incidence_full %>%
  filter(status == "in-patient") %>%
  mutate(week_admitted = yearweek(date_admitted)) %>%
  group_by(week_admitted) %>%
  tally() %>%
  mutate(frame = "p2")

p2 <- p2_df %>%
  ggplot() +
  geom_step(aes(x = week_admitted, y = n)) +
  scale_x_yearweek(
    "Week admitted",
    breaks = as.Date(as.character(2000:2023), format = "%Y"),
    date_labels = "%Y",
  ) +
  scale_y_continuous("Case admission") +
  ggtitle("Weekly dengue case admission in HCMC (in-patient only)")
p2
```



# Time series - grouped

```{r fig.width=10}
incidence_full_renamed %>%
  ggplot() +
  geom_line(aes(x = date_admitted, y = n, color = hospital, group = hospital)) +
  theme(legend.position = "none") +
  scale_x_yearweek(
    # "Tuần nhập viện",
    "Week admitted",
    breaks = as.Date(as.character(2000:2023), format = "%Y"),
    date_label = "%Y"
  ) +
  # scale_y_continuous("Tổng số ca nhập viện trong tuần", breaks = seq(0, 350, 50)) +
  scale_y_continuous("Case admission", breaks = seq(0, 350, 50)) +
  # ggtitle("Tổng số ca SXHD nhập viện theo tuần theo từng bệnh viện")
  ggtitle("Weekly dengue case admission per hospital")

# plotly::ggplotly(.Last.value)
```

```{r}
temp <- incidence_full_renamed %>%
  mutate(n = ifelse(is.na(n), 0, n)) %>%
  group_by(hospital) %>%
  summarise(n = sum(n))

(temp %>%
  filter(hospital == "bênh viện bệnh nhiệt đới tphcm") %>%
  pull(n)) / sum(temp$n)

(temp %>%
  filter(hospital == "bệnh viện nhi đồng 2") %>%
  pull(n)) / sum(temp$n)
```


# Total presence

```{r fig.height=10, fig.width=20}
incidence_full_renamed %>%
  replace_na(list(n = 0)) %>%
  mutate(presence = ifelse(n > 0, 1, 0), date_admitted = as.Date(date_admitted)) %>%
  group_by(hospital) %>%
  summarise(total_presence = sum(presence)) %>%
  mutate(hospital = fct_reorder(hospital, total_presence)) %>%
  arrange(desc(total_presence))
```


```{r}
incidence_full_presence_group <- incidence_full_renamed %>%
  replace_na(list(n = 0)) %>%
  mutate(presence = ifelse(n > 0, 1, 0), date_admitted = as.Date(date_admitted)) %>%
  group_by(hospital) %>%
  mutate(
    total_presence = sum(presence),
    group = case_when(
      total_presence > 500 ~ 1,
      total_presence > 50 ~ 2,
      total_presence > 0 ~ 3
    )
  ) %>%
  group_by(group) %>%
  mutate(hospital = fct_reorder(hospital, total_presence))
```

## Bar chart
```{r fig.height=15, fig.width=15}
incidence_full_presence_group %>%
  count(hospital, presence) %>%
  pivot_wider(id_cols = c(group, hospital), names_from = presence, values_from = n) %>%
  ungroup() %>%
  mutate(hospital = fct_reorder(hospital, -`0`)) %>%
  ggplot() +
  geom_col(aes(y = hospital, x = `0`)) +
  coord_cartesian(xlim = range(`0`)) +
  # scale_x_continuous("Số tuần \"vắng\"") +
  scale_x_continuous("Weeks of \"Absence\"") +
  # scale_y_discrete("Bệnh viện") +
  scale_y_discrete("Hospital") +
  # ggtitle("Bệnh viện theo số lượng tuần \"vắng\"")
  ggtitle("The number of \"absence\" weeks per hospital")
```

## Hit map
```{r fig.height=20, fig.width=20}
incidence_full_presence_group %>%
  mutate(
    presence = as.factor(presence)
  ) %>%
  ggplot() +
  geom_raster(aes(x = date_admitted, y = hospital, fill = presence)) +
  scale_x_yearweek(
    # "Tuần nhập viện",
    "Week admitted",
    breaks = as.Date(as.character(seq(2000, 2023)), format = "%Y"),
    date_label = "%Y"
  ) +
  # scale_y_discrete("Bệnh viện") +
  scale_y_discrete("Hospital") +
  facet_wrap(~group, ncol = 1, scales = "free") +
  theme(legend.position = "none") +
  # ggtitle("Số tuần \"hiện diện\" và \"vắng\" của từng bệnh viện theo thời gian")
  ggtitle("Hit map of hospital presence and abscene weeks over time")
```

## Scatter plot
```{r fig.height=7, fig.width=13}
incidence_full_presence_group %>%
  group_by(hospital) %>%
  select(hospital, presence, n) %>%
  summarise(with_data = sum(presence), total_incidence = sum(n)) %>%
  ggplot(aes(y = with_data, x = total_incidence)) +
  geom_point() +
  geom_smooth(method = "loess", formula = y ~ x) +
  # scale_y_continuous("Số tuần có sự \"hiện diện\"") +
  scale_y_continuous("Weeks of presence") +
  # scale_x_log10("Tổng số ca bệnh", breaks = 10^(0:5), labels = scales::label_log()) +
  scale_x_log10("Total case admission", breaks = 10^(0:5), labels = scales::label_log()) +
  # ggtitle("Mối quan hệ giữa số tuần có \"sự hiện diện\" và tổng số ca bệnh của các bệnh viện")
  ggtitle("Relationship between presence weeks and total case admission")
```

## Map

```{r}
hospital_groups <- incidence_full_presence_group %>%
  select(hospital, group) %>%
  distinct()
```


```{r}
hospitals_geocoded <- hospital_groups %>%
  mutate(hospital = str_replace_all(hospital, c("tphcm" = "", "tp.hcm" = ""))) %>%
  mutate(hospital = paste0(hospital, ", tp hồ chí minh")) %>%
  tidygeocoder::geocode(
    hospital,
    method = "arcgis", lat = lat, lon = lon
  )
```

```{r}
hospitals_geocoded
```

```{r fig.height=10, fig.width=10}
shp_lvl3 <- readRDS("utils/gadm/gadm41_VNM_3_pk.rds") %>%
  terra::unwrap() %>%
  st_as_sf() %>%
  filter(GID_1 == "VNM.25_1")

ggplot() +
  geom_sf(data = shp_lvl3) +
  geom_point(data = hospitals_geocoded, aes(x = lon, y = lat, color = as.factor(group))) +
  # scale_x_continuous("Kinh độ") +
  # scale_y_continuous("Vĩ độ") +
  # scale_color_discrete("Nhóm")
  scale_x_continuous("Longitude") +
  scale_y_continuous("Latitude") +
  scale_color_discrete("Group")
```

### Moran's I

```{r}
hosp_coords <- hospitals_geocoded %>%
  select(lon, lat) %>%
  sp::coordinates()
hosp_ids <- row.names(as.data.frame(hosp_coords))

# Chosing a distance d such that pairs of points with distances less than
# d are neighbors and those further apart are not

neighbors <- knn2nb(
  knearneigh(hosp_coords, k = 1, longlat = TRUE),
  row.names = hosp_ids
)

neighbors

# assigns at least one neighbor to each and calculates the distances between
# returns the distance between nearest neighbors for each point
dists <- unlist(nbdists(neighbors, hosp_coords))
summary(dists)

# maximum distance to provide at least one neighbor to each point
max_1n <- max(dists)
max_1n

# Create different neighbor structures based upon distance

# neighbors within maximum distance
neigh_d1 <- dnearneigh(hosp_coords, d1 = 0, d2 = max_1n, row.names = hosp_ids)
# neighbors within 2X maximum distance
neigh_d2 <- dnearneigh(hosp_coords, d1 = 0, d2 = 2 * max_1n, row.names = hosp_ids)

nb_1 <- list(d1 = neigh_d1, d2 = neigh_d2) # list of neighbor structures
sapply(nb_1, function(x) is.symmetric.nb(x, verbose = F, force = T))

# Checks for symmetry (i.e. if i is a neighbor of j, then j is a neighbor of i). Does not always hold for k-nearest neighbours
sapply(nb_1, function(x) n.comp.nb(x)$nc)

par(mfrow = c(2, 1), mar = c(1, 0, 1, 0))
plot(hosp_coords, pch = 16)
plot(neigh_d1, hosp_coords, col = "green", add = T)
plot(hosp_coords, pch = 16)
plot(neigh_d2, hosp_coords, col = "green", add = T)

# assign weights;
# row standardized binary weights, using minimum distance for one neighbor
weights <- nb2listw(neigh_d1, style = "W")
# "B" is simplest binary weights
weights

moran.test(hospitals_geocoded$group, listw = weights) # using row standardised weights
```
