---
output: 
  html_document:
    df_print: paged
    toc: yes
    theme: journal
---

**Knitted at: `r Sys.time()`**

# Libraries and functions
```{r message=FALSE, warning=FALSE}
.pkgs <- c("tidyverse", "magrittr", "rsample", "tsibble", "modelr", "furrr", "distributional", "scoringRules")
xfun::pkg_attach(.pkgs, message = FALSE)

source("../utils/cross_validation.R", chdir = TRUE)
source("../utils/boot_pi.R", chdir = TRUE)
```

# Settings
```{r}
theme_set(theme_bw())
set.seed(123)
```

# Data ingestion
```{r}
incidence_weekly_weather_df <- read_rds("../utils/data_weekly_rds-s/incidence_weekly_weather_df.rds")
```

## Feature engineering

```{r}
incidence_ww_trunc_df <- incidence_weekly_weather_df
covar_names <- colnames(incidence_ww_trunc_df)[-c(1, 2)]

# 3 months incidence lag
incidence_ww_trunc_df %<>% calculate_lags("n", 1:12)
for (covar in covar_names) {
  incidence_ww_trunc_df %<>% calculate_lags(covar, 1:12)
}

# truncate date, remove temporal data
incidence_ww_trunc_df %<>%
  filter_index("2004 W01" ~ "2019 W52") %>%
  as_tibble() %>%
  mutate(week = isoweek(date_admitted), month = month(date_admitted), year = year(date_admitted)) %>%
  select(-date_admitted) %>%
  rowid_to_column()

incidence_ww_trunc_df
```

## Train test splitting

```{r}
dat_split <- initial_split(incidence_ww_trunc_df, strata = year)
train_dat <- training(dat_split)
test_dat <- testing(dat_split)

ggplot(mapping = aes(x = rowid, y = n)) +
  geom_point(data = train_dat, alpha = 0.8) +
  geom_point(data = test_dat, color = "red", alpha = 0.8)
```


# Modelling

## Autoregression
```{r}
ar_formula <- as.formula(paste0("n ~ ", paste("n_lag", 1:12, sep = "", collapse = " + ")))

plan(multisession, workers = 7)
ar_perfs <- rep_kfold_cv_glm(ar_formula, train_dat)
plan(sequential)
```

```{r}
ar_perfs_df <- ar_perfs %>%
  as_tibble() %>%
  mutate(rep = rep(seq_len(5), each = 5), k = rep(1:5, 5), .before = everything()) %>%
  pivot_longer(-c(rep, k))
```

```{r}
ar_perfs_df %>%
  ggplot(aes(y = value, x = rep, color = name)) +
  geom_point() +
  stat_summary(
    fun = mean, geom = "errorbar", color = "black",
    aes(ymax = after_stat(y), ymin = after_stat(y), width = 0.5)
  ) +
  facet_wrap(~name, scales = "free_y") +
  scale_x_continuous(minor_breaks = NULL) +
  guides(color = "none")
```

```{r}
ar_perfs_df %>% ggplot(aes(y = value, x = name, color = name)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  guides(color = "none")
```

## All covariables

```{r}
covar_formula <- as.formula(paste0("n ~ ", paste(covar_names, collapse = " + ")))

plan(multisession, workers = 7)
covar_perfs <- rep_kfold_cv_glm(covar_formula, train_dat)
plan(sequential)
```

```{r}
covar_perfs_df <- covar_perfs %>%
  as_tibble() %>%
  mutate(rep = rep(seq_len(5), each = 5), k = rep(1:5, 5), .before = everything()) %>%
  pivot_longer(-c(rep, k))
covar_perfs_df
```

```{r}
covar_perfs_df %>%
  ggplot(aes(y = value, x = rep, color = name)) +
  geom_point() +
  stat_summary(
    fun = mean, geom = "errorbar", color = "black",
    aes(ymax = after_stat(y), ymin = after_stat(y), width = 0.5)
  ) +
  facet_wrap(~name, scales = "free_y") +
  scale_x_continuous(minor_breaks = NULL) +
  guides(color = "none")
```

```{r}
covar_perfs_df %>% ggplot(aes(y = value, x = name, color = name)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  guides(color = "none")
```

## All lagged covariables (distributed lag model)

```{r}
dlm_covar_names <- colnames(incidence_ww_trunc_df %>% select(-c(rowid, contains("n"), week, month)))
dlm_formula <- as.formula(paste0("n ~ ", paste(dlm_covar_names, collapse = " + ")))

plan(multisession, workers = 7)
dlm_perfs <- rep_kfold_cv_glm(dlm_formula, train_dat)
plan(sequential)
```

```{r}
dlm_perfs_df <- dlm_perfs %>%
  as_tibble() %>%
  mutate(rep = rep(seq_len(5), each = 5), k = rep(1:5, 5), .before = everything()) %>%
  pivot_longer(-c(rep, k))
dlm_perfs_df
```

```{r}
dlm_perfs_df %>%
  ggplot(aes(y = value, x = rep, color = name)) +
  geom_point() +
  stat_summary(
    fun = mean, geom = "errorbar", color = "black",
    aes(ymax = after_stat(y), ymin = after_stat(y), width = 0.5)
  ) +
  facet_wrap(~name, scales = "free_y") +
  scale_x_continuous(minor_breaks = NULL) +
  guides(color = "none")
```

```{r}
dlm_perfs_df %>% ggplot(aes(y = value, x = name, color = name)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  guides(color = "none")
```


## Comparing

```{r}
all_perfs_df <- ar_perfs_df %>%
  mutate(from = "ar") %>%
  bind_rows(
    covar_perfs_df %>% mutate(from = "covar")
  ) %>%
  bind_rows(
    dlm_perfs_df %>% mutate(from = "dlm")
  )

all_perfs_df %>% filter(name == "pdf") %>% ggplot() +
  geom_boxplot(aes(x = name, y = value, fill = from))
```
