---
output: 
  html_document:
    df_print: paged
    toc: yes
    theme: journal
---

# Library

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)

library(feasts)
library(tsibble)
library(fable.prophet)
library(fabletools)
library(fable)

library(lubridate)

library(ggdist)

library(sf)
library(stars)
```


# Data ingestion

## Incidence data

```{r}
incidence_raw <- read_csv("../incidence_ts_in.csv", show_col_types = FALSE) %>%
  mutate(date_admitted = as.Date(date_admitted)) %>%
  as_tsibble(index = date_admitted) %>%
  fill_gaps(n = 0)

incidence_weekly_df <- incidence_raw %>%
  index_by(agg = ~ yearweek(.)) %>%
  summarise(n = sum(n)) %>%
  rename(date_admitted = agg)

train_weekly_df <- incidence_weekly_df %>%
  filter(year(date_admitted) < 2019)

ggplot(incidence_weekly_df, aes(x = date_admitted, y = n)) +
  geom_line()
```

## HCMC shape

```{r}
hcmc_shp <- read_rds("../gadm/gadm41_VNM_1_pk.rds") %>%
  terra::unwrap() %>%
  st_as_sf() %>%
  filter(GID_1 == "VNM.25_1")

hcmc_shp_w_buff <- st_buffer(hcmc_shp, units::set_units(10, "km"))
```

## Temperature data
```{r}
hcmc_temp_2019 <- read_stars("../2m_temp_HCMC.nc") %>%
  st_set_crs(4326) %>%
  aggregate(hcmc_shp_w_buff, FUN = mean) %>%
  aggregate("1 week", FUN = mean) %>%
  as_tibble() %>%
  select(time, `2m_temp_HCMC.nc`) %>%
  rename(date = time, t2m = `2m_temp_HCMC.nc`) %>%
  mutate(date = as.Date(date) %>% yearweek(), t2m = t2m - 273.15) %>%
  as_tsibble()

hcmc_temp_2019 %>%
  ggplot(aes(x = date, y = t2m)) +
  geom_line() +
  geom_smooth()
```

# Data transformation

## Log transformation
```{r}
incidence_weekly_df %<>% mutate(n = log(n))
train_weekly_df %<>% mutate(n = log(n))

ggplot(incidence_weekly_df, aes(x = date_admitted, y = n)) +
  geom_line()
```



# Weekly models

## SARIMA weekly

### Differencing
Quickly check if any differencing needed, both seasonal and non-seasonal
```{r}
train_weekly_df %>% features(n, unitroot_ndiffs)
train_weekly_df %>% features(n, unitroot_nsdiffs)
```

```{r}
train_weekly_df %>%
  gg_tsdisplay(
    difference(n),
    plot_type = "partial",
    lag = 52
  )

train_weekly_df %>%
  gg_tsdisplay(
    difference(n, 52),
    plot_type = "partial",
    lag = 208
  )
```

### Model fitting

```{r}
future::plan(future::multisession)

sarima_fits <- train_weekly_df %>% model(
  auto_arima = ARIMA(n ~ pdq(2, 0, 1) + PDQ(1, 1, 0)),

  # same as auto_arima but with non-seasonal differencing
  arima_211110 = ARIMA(n ~ pdq(2, 1, 1) + PDQ(1, 1, 0))
)

future::plan(future::sequential())
```

```{r}
report(sarima_fits)

accuracy(sarima_fits)

fit <- sarima_fits %>% select(auto_arima)

# residuals
fit %>% gg_tsresiduals(lag = 104)

fit_resid <- fit %>%
  residuals() %>%
  as_tibble()

shapiro.test(fit_resid$.resid)
skedastic::white(lm(.resid ~ date_admitted, data = fit_resid))
```


```{r}
sarima_fits %>%
  augment() %>%
  features(.innov, ljung_box, lag = min(2 * 52, nrow(train_weekly_df) / 5), dof = 3)
```

### Forecast
```{r}
forecasted_sarima <- forecast(sarima_fits, h = 52)

incidence_2019_weekly_df <- incidence_weekly_df %>% filter(year(date_admitted) == 2019)

forecast_p <- forecasted_sarima %>%
  autoplot(incidence_2019_weekly_df) +
  scale_x_yearweek(date_breaks = "3 months", date_labels = "%b")

forecast_p + facet_wrap(~.model)
```


```{r}
forecasted_sarima %>% accuracy(incidence_2019_weekly_df)
```

## SARIMA one-week-ahead

```{r}
fit <- sarima_fits %>% select(auto_arima)

forecast_1w_df <- train_weekly_df %>% mutate(ci = NA)

for (i in 1:52) {
  forecasted_1w <- fit %>%
    forecast(h = 1) %>%
    as_tibble() %>%
    select(date_admitted, .mean, n) %>%
    rename(ci = n, n = .mean)

  forecast_1w_df %<>% tail(-1) %>% bind_rows(forecasted_1w)

  fit %<>% refit(forecast_1w_df, reestimate = FALSE)
}

ggplot(mapping = aes(x = date_admitted)) +
  stat_lineribbon(
    data = forecast_1w_df,
    aes(ydist = ci),
    linewidth = .5,
    .width = c(0.8, 0.95),
    color = "blue"
  ) +
  geom_line(
    data = incidence_weekly_df,
    aes(y = n)
  ) +
  scale_fill_brewer() +
  scale_x_yearweek(limit = c(as.Date("2018-01-01"), as.Date("2020-01-01")))
```

### Accuracy
```{r}
actual <- incidence_weekly_df %>%
  filter(year(date_admitted) == 2019) %>%
  pull(n)
forecasted <- forecast_1w_df %>%
  filter(year(date_admitted) == 2019) %>%
  pull(n)

sprintf(
  "RMSE: %f",
  sqrt(mean((actual - forecasted)^2))
)
sprintf(
  "MAE: %f",
  mean(abs(actual - forecasted))
)
```


## Prophet weekly

```{r}
prophet_weekly <- train_weekly_df %>%
  model(
    prophet_addi = prophet(n ~ season(period = 52, order = 10, type = "additive")),
    prophet_multi = prophet(n ~ season(period = 52, order = 10, type = "multiplicative"))
  )

prophet_weekly_forecast <- prophet_weekly %>%
  forecast(h = 52)

prophet_forecast_p <- prophet_weekly_forecast %>%
  autoplot(incidence_2019_weekly_df) +
  scale_x_yearweek(date_breaks = "3 months", date_labels = "%b")

prophet_forecast_p
prophet_forecast_p + facet_wrap(~.model)

accuracy(prophet_weekly_forecast, incidence_2019_weekly_df)
```

### With holidays

```{r fig.height=15, fig.width=15, warning=FALSE}
lunR::lunar_to_gregorian("2001-12-29")


pub_holidays <- map(2000:2022, \(year){
  c(
    sprintf("%d-01-01", year),
    sprintf("%d-12-29", subtract(year, 1)) %>% lunR::lunar_to_gregorian(),
    sprintf("%d-03-10", year) %>% lunR::lunar_to_gregorian(),
    sprintf("%d-04-30", year),
    sprintf("%d-05-01", year),
    sprintf("%d-09-02", year)
  )
}) %>%
  list_c() %>%
  as.Date()

vn_pub_holidays <- tsibble(
  date = pub_holidays,
  holiday = rep(
    c("New Year", "Tet", "Hung King", "Reunification", "Labor Day", "Independence Day"),
    23
  ),
  lower_window = rep(c(0, 0, 0, 0, 0, 0), 23),
  upper_window = rep(c(1, 7, 1, 1, 1, 2), 23),
  index = date
)

vn_pub_holidays_train <- vn_pub_holidays %>% filter(year(date) < 2019)

incidence_weekly_df %>%
  mutate(year = year(date_admitted)) %>%
  autoplot() +
  geom_vline(data = vn_pub_holidays, aes(xintercept = date), color = "red", alpha = 0.3) +
  facet_wrap(~year, scales = "free_x")
```

```{r}
prophet_weekly_w_holiday <- train_weekly_df %>%
  model(
    prophet_w_holiday = prophet(
      n ~ season(period = 52, order = 10, type = "additive") +
        holiday(vn_pub_holidays_train)
    )
  )

prophet_weekly_forecast <- prophet_weekly_w_holiday %>%
  forecast(h = 52)

prophet_weekly_forecast %>%
  autoplot(incidence_2019_weekly_df) +
  geom_vline(data = vn_pub_holidays, aes(xintercept = date), color = "red", alpha = 0.1)

accuracy(prophet_weekly_forecast, incidence_2019_weekly_df)
```

## SARIMAX

```{r}
train_weekly_t2m_df <- train_weekly_df %>% left_join(hcmc_temp_2019, by = c("date_admitted" = "date"))

sarimax_fit <- train_weekly_t2m_df %>% model(
  auto_arima = ARIMA(n ~ xreg(t2m) + pdq(2, 0, 1) + PDQ(1, 1, 0)),
)
```


### Fit performance
```{r}
report(sarimax_fit)

accuracy(sarimax_fit)

# residuals
sarimax_fit %>% gg_tsresiduals(lag = 104)

fit_resid <- sarimax_fit %>%
  residuals() %>%
  as_tibble()

shapiro.test(fit_resid$.resid)
skedastic::white(lm(.resid ~ date_admitted, data = fit_resid))


sarimax_fit %>%
  augment() %>%
  features(.innov, ljung_box, lag = min(2 * 52, nrow(train_weekly_df) / 5), dof = 3)
```


### Forecasting
```{r}
forecasted_sarimax <- forecast(
  sarimax_fit,
  new_data = hcmc_temp_2019 %>% filter(year(date) == 2019),
  h = 52
)

incidence_2019_weekly_df <- incidence_weekly_df %>%
  filter(year(date_admitted) == 2019) %>%
  rename(date = date_admitted)

forecast_p <- forecasted_sarimax %>%
  autoplot(incidence_2019_weekly_df) +
  scale_x_yearweek(date_breaks = "3 months", date_labels = "%b")

forecast_p

accuracy(forecasted_sarimax, incidence_2019_weekly_df)
```
