---
output: 
  html_document:
    df_print: paged
    toc: yes
    theme: journal
---

**Knitted at: `r Sys.time()`**

# Library

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)

library(feasts)
library(tsibble)
library(fable.prophet)
library(fabletools)
library(fable)

library(lubridate)

library(ggdist)

library(sf)
library(stars)

library(parallel)
```

```{r}
theme_set(theme_bw())
```

# Data ingestion

```{r}
# setwd("time_series_modelling")
source("../data_weekly.R", chdir = TRUE)
```


## Incidence data

```{r}
ggplot(incidence_weekly_df, aes(x = date_admitted, y = n)) +
  geom_step() +
  scale_x_yearweek("Week of admission") +
  scale_y_continuous("Case admitted") +
  ggtitle("Dengue weekly incidence")
```

```{r}
train_weekly_df <- train_weekly_df %>% bind_rows(val_weekly_df)
train_weekly_df %>% tail()
```


# Modelling

## Framework

### Performance checking 

```{r}
fit_perf <- function(fit, actual) {
  print(summary(fit))

  fitted <- fitted(fit)

  fitted %>% plot(type = "l")

  print(sprintf(
    "Train RMSE: %f",
    sqrt(mean((actual - fitted)^2))
  ))
  print(sprintf(
    "Train MAE: %f",
    mean(abs(actual - fitted))
  ))

  print(train_weekly_weather_df %>%
    mutate(fitted = fitted) %>%
    ggplot(aes(x = date_admitted)) +
    geom_line(aes(y = n)) +
    geom_line(aes(y = fitted), color = "red"))
}

model_perfs <- tibble(
  model = character(),
  RMSE = numeric(),
  MAE = numeric()
)

forecast_perf <- function(forecast, actual, model_name) {
  rmse <- sqrt(mean((actual - forecast)^2))
  mae <- mean(abs(actual - forecast))

  print(sprintf("Test RMSE: %f", rmse))
  print(sprintf("Test MAE: %f", mae))

  model_perfs <<- model_perfs %>%
    bind_rows(tibble(model = model_name, RMSE = rmse, MAE = mae))
}
```

### Forecast framework
```{r}
forecast_layer <- function(frcst_df, funnel = TRUE) {
  frcst_df %<>%
    group_by(startweek)

  if (funnel) {
    frcst_df %<>%
      group_map(\(.x, .y){
        target_date <- min(.x$date_admitted) - 1
        target_row <- incidence_weekly_df %>%
          filter(date_admitted == target_date) %>%
          mutate(.mean = n, uppers = n, lowers = n, startweek = .y$startweek)

        .x %>%
          mutate(startweek = .y$startweek) %>%
          add_row(
            target_row,
            .before = 0
          )
      }) %>%
      list_c() %>%
      group_by(startweek)
  }

  lapply(
    frcst_df %>% group_split(),
    \(df)
    c(layer(
      data = df,
      geom = "ribbon", stat = "identity", position = "identity",
      mapping = aes(x = date_admitted, ymin = lowers, ymax = uppers),
      params = list(alpha = 0.5, fill = "pink")
    ), layer(
      data = df,
      geom = "line", stat = "identity", position = "identity",
      mapping = aes(x = date_admitted, y = .mean), params = list(color = "red")
    ))
  )
}

forecast_chunks <- function(
    train_set, test_set,
    start_indices,
    model_fn, formula,
    horizon = 4, cl = NULL) {
  if (!missing(cl)) {
    clusterExport(cl, c("train_set", "test_set"), environment())
  }
  model_fn <- match.fun(model_fn)

  pbapply::pblapply(start_indices, \(start_idx){
    train_df <- train_set %>%
      bind_rows(test_set %>% slice_head(n = start_idx)) %>%
      tail(nrow(train_set))


    fit <- train_df %>% model(model = model_fn(!!enquo(formula)))

    fit %>%
      forecast(h = horizon) %>%
      as_tibble() %>%
      mutate(
        .model = format(fit$model),
        startweek = start_idx,
        uppers = hilo(n)$upper,
        lowers = hilo(n)$lower
      )
  }, cl = cl) %>%
    list_c()
}
```

## Mean

```{r}
mean_fit <- forecast_chunks(
  train_weekly_df, test_weekly_df, seq(0, 49, 3), MEAN, n
)

ggplot(test_weekly_df) +
  geom_line(aes(x = date_admitted, y = n)) +
  forecast_layer(mean_fit, funnel = FALSE) +
  scale_x_yearweek(
    "Week",
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - MEAN")

ggsave("./svgs/forecast_mean_4w.svg", width = 10, height = 7)
```

```{r}
pre_perf <- mean_fit %>%
  select(date_admitted, .mean) %>%
  left_join(test_weekly_df, by = "date_admitted")

forecast_perf(pre_perf$.mean, pre_perf$n, "MEAN")
```


## Seasonal mean

```{r}
smean_forecast <- train_weekly_df %>%
  as_tibble() %>%
  mutate(
    week = week(date_admitted),
    year_w = year(date_admitted) - 1999,
    year_w_exp = exp(year_w)
  ) %>%
  group_by(week) %>%
  summarise(
    smean = mean(n),
    smean_w = weighted.mean(n, year_w),
    smean_w_exp = weighted.mean(n, year_w_exp)
  ) %>%
  head(-1) %>%
  mutate(
    date_admitted = test_weekly_df$date_admitted,
    .before = everything()
  ) %>%
  select(-week) %>%
  as_tsibble(index = "date_admitted")

smean_forecast %>%
  pivot_longer(-date_admitted) %>%
  ggplot(aes(x = date_admitted)) +
  geom_line(aes(y = value, color = name, group = name)) +
  geom_line(data = incidence_weekly_df, mapping = aes(y = n)) +
  scale_x_yearweek(
    "Week",
    limits = c(
      as.Date(min(test_weekly_df$date_admitted)),
      as.Date(max(test_weekly_df$date_admitted))
    ),
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - Seasonal mean")

ggsave("./svgs/forecast_smean_4w.svg", width = 10, height = 7)

forecast_perf(
  smean_forecast %>% head(4) %>% as_tibble() %>% pull(smean),
  test_weekly_weather_df %>% pull(n),
  "Seasonal mean"
)

forecast_perf(
  smean_forecast %>% head(4) %>% as_tibble() %>% pull(smean_w),
  test_weekly_weather_df %>% pull(n),
  "Seasonal mean weighted"
)

forecast_perf(
  smean_forecast %>% head(4) %>% as_tibble() %>% pull(smean_w_exp),
  test_weekly_weather_df %>% pull(n),
  "Seasonal mean exponentially weighted"
)
```

## NAIVE
```{r}
naive_fit <- forecast_chunks(train_weekly_df, test_weekly_df, seq(0, 49, 3), NAIVE, n)

ggplot(test_weekly_df) +
  geom_line(aes(x = date_admitted, y = n)) +
  forecast_layer(naive_fit) +
  scale_x_yearweek(
    "Week",
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - NAIVE")

ggsave("./svgs/forecast_naive_4w.svg", width = 10, height = 7)
```


```{r}
pre_perf <- naive_fit %>%
  select(date_admitted, .mean) %>%
  left_join(test_weekly_df, by = "date_admitted")

forecast_perf(pre_perf$.mean, pre_perf$n, "NAIVE")
```

## SNAIVE

```{r}
snaive_fit <- train_weekly_df %>% model(SNAIVE(n))

snaive_fit %>%
  forecast(h = 52) %>%
  autoplot(test_weekly_df, level = 95, color = "red") +
  scale_x_yearweek(
    "Week",
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - SNAIVE") +
  theme(legend.position = "none")

ggsave("./svgs/forecast_snaive_4w.svg", width = 10, height = 7)

forecast_perf(
  snaive_fit %>% forecast(h = 4) %>% as_tibble() %>% pull(.mean),
  test_weekly_weather_df %>% pull(n),
  "SNAIVE"
)
```

## Drift

```{r}
# start <- train_weekly_df %>% head(1)
# end <- train_weekly_df %>% tail(1)
#
# p <- incidence_weekly_df %>% ggplot() +
#   geom_line(aes(x = date_admitted, y = n)) +
#   geom_segment(aes(x = start$date_admitted, y = start$n, xend = end$date_admitted, yend = end$n))
#
# plotly::ggplotly(p)
```


```{r}
drift_fit <- forecast_chunks(
  train_weekly_df, test_weekly_df, seq(0, 49, 3), RW, n ~ drift()
)

ggplot(test_weekly_df) +
  geom_line(aes(x = date_admitted, y = n)) +
  forecast_layer(drift_fit) +
  scale_x_yearweek(
    "Week",
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - DRIFT")

ggsave("./svgs/forecast_drift_4w.svg", width = 10, height = 7)
```


```{r}
pre_perf <- drift_fit %>%
  select(date_admitted, .mean) %>%
  left_join(test_weekly_df, by = "date_admitted")

forecast_perf(pre_perf$.mean, pre_perf$n, "Drift")
```

## AR

```{r}
ar_fit <- forecast_chunks(train_weekly_df, test_weekly_df, seq(0, 49, 3), AR, n)

ggplot(test_weekly_df) +
  geom_line(aes(x = date_admitted, y = n)) +
  forecast_layer(ar_fit) +
  scale_x_yearweek(
    "Week",
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - AR(10)")

ggsave("./svgs/forecast_ar10_4w.svg", width = 10, height = 7)
```

```{r}
pre_perf <- ar_fit %>%
  select(date_admitted, .mean) %>%
  left_join(test_weekly_df, by = "date_admitted")

forecast_perf(pre_perf$.mean, pre_perf$n, "AR(10)")
```

## MA

```{r}
ma_fit <- forecast_chunks(
  train_weekly_df, test_weekly_df, seq(0, 49, 3), ARIMA, n ~ pdq(0, 0, 6) + PDQ(0, 0, 0)
)

ggplot(test_weekly_df) +
  geom_line(aes(x = date_admitted, y = n)) +
  forecast_layer(ma_fit) +
  scale_x_yearweek(
    "Week",
    breaks = test_weekly_df$date_admitted[seq(0, 52, 3) + 1],
    labels = as.character(test_weekly_df$date_admitted[seq(0, 52, 3) + 1]) %>% str_extract("W\\d+"),
    minor_breaks = NULL
  ) +
  scale_y_continuous("Incidence") +
  ggtitle("4 week forecast - MA(6)")

ggsave("./svgs/forecast_ma6_4w.svg", width = 10, height = 7)
```


```{r}
pre_perf <- ma_fit %>%
  select(date_admitted, .mean) %>%
  left_join(test_weekly_df, by = "date_admitted")

forecast_perf(pre_perf$.mean, pre_perf$n, "MA(6)")
```

# Comparison
```{r}
model_perfs %>% arrange(RMSE)
```

```{r}
model_perfs %>% write_csv("simple_models_perf.csv")
```
